### ISSUE TITLE
Build instructions in README or a binary release?

### ISSUE THREAD

**Issue by DanielSmedegaardBuus** [mungler/PoolFS#1]
Hi :)

Was looking for an AuFS alternative, and found your project. Unfortunately, I'm completely lost when it comes to Xcode and Objective-C, and I don't know how to build the thing. Also, there aren't any release on the page...

Any chance of either the README containing build instructions, or a binary being offered on the releases tab?

Cheers :)
Daniel

**Comment by mungler** [comment]
Hi Daniel,

Wow, talk about a blast from the past! I haven't done any work on this in over 8 years so I'm afraid I can't even remember much about how it works. I think there were changes to how MacFUSE worked shortly after I did this which broke it, and I gave up. 

Looks like someone forked it - maybe their fork is a better starting point? https://github.com/simphax/PoolFS

Good luck!
